import logging
import uuid
from sqlmodel import Session, select
from app.db.session import get_session # For FastAPI endpoints
from app.models.pipeline_models import (
    PipelineRun, PipelineRunCreate, PipelineRunRead, PipelineRunStatus, PipelineType
)
from app.models.file_models import UploadedFileLog
from app.tasks.summarization_tasks import summarize_pdf_task # Import the Celery task
from fastapi import HTTPException, Depends
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

async def create_and_dispatch_summary_pipeline(
    uploaded_file_log_id: int,
    db: Session = Depends(get_session)
) -> PipelineRunRead:
    """
    Creates a PipelineRun entry for PDF summarization and dispatches the Celery task.
    """
    # 1. Verify UploadedFileLog exists
    uploaded_file = db.get(UploadedFileLog, uploaded_file_log_id)
    if not uploaded_file:
        raise HTTPException(status_code=404, detail=f"UploadedFileLog with id {uploaded_file_log_id} not found.")

    # 2. Create PipelineRun entry
    pipeline_run_create = PipelineRunCreate(
        pipeline_name=PipelineType.PDF_SUMMARIZER,
        status=PipelineRunStatus.QUEUED,
        uploaded_file_log_id=uploaded_file_log_id
    )
    db_pipeline_run = PipelineRun.model_validate(pipeline_run_create)
    # db_pipeline_run.run_uuid is generated by default_factory
    
    db.add(db_pipeline_run)
    db.commit()
    db.refresh(db_pipeline_run)
    logger.info(f"Created PipelineRun {db_pipeline_run.run_uuid} for file_log_id {uploaded_file_log_id}.")

    # 3. Dispatch Celery task
    try:
        # Ensure pdf_path is correctly retrieved from uploaded_file.storage_location
        pdf_path = uploaded_file.storage_location
        if not pdf_path:
             db_pipeline_run.status = PipelineRunStatus.FAILED
             db_pipeline_run.error_message = "PDF path not found in UploadedFileLog."
             db_pipeline_run.updated_at = datetime.now(timezone.utc)
             db.add(db_pipeline_run)
             db.commit()
             # No refresh here, as we are raising immediately
             raise HTTPException(status_code=500, detail="PDF path not found for dispatching task.")

        task_result = summarize_pdf_task.delay(
            str(db_pipeline_run.run_uuid),
            uploaded_file.id,
            pdf_path,
            uploaded_file.filename
        )
        
        # 4. Store Celery task ID
        db_pipeline_run.celery_task_id = task_result.id
        db_pipeline_run.updated_at = datetime.now(timezone.utc) # Update timestamp after getting task_id
        db.add(db_pipeline_run)
        db.commit()
        db.refresh(db_pipeline_run)
        logger.info(f"Dispatched Celery task {task_result.id} for PipelineRun {db_pipeline_run.run_uuid}.")
        
    except HTTPException as he: # Specifically catch and re-raise HTTPExceptions
        raise he
    except Exception as e:
        logger.error(f"Failed to dispatch Celery task for PipelineRun {db_pipeline_run.run_uuid}: {e}")
        # Update PipelineRun to FAILED status if dispatch fails
        db_pipeline_run.status = PipelineRunStatus.FAILED
        db_pipeline_run.error_message = f"Failed to dispatch Celery task: {str(e)}"
        db_pipeline_run.updated_at = datetime.now(timezone.utc)
        db.add(db_pipeline_run)
        db.commit()
        db.refresh(db_pipeline_run)
        # Re-raise or handle appropriately, maybe return an error response model
        raise HTTPException(status_code=500, detail=f"Failed to dispatch summarization task: {str(e)}")

    return PipelineRunRead.model_validate(db_pipeline_run)

async def get_pipeline_run_status(run_uuid: uuid.UUID, db: Session = Depends(get_session)) -> PipelineRunRead | None:
    """
    Retrieves the status of a specific pipeline run.
    """
    statement = select(PipelineRun).where(PipelineRun.run_uuid == run_uuid)
    db_pipeline_run = db.exec(statement).one_or_none()
    if not db_pipeline_run:
        return None
    return PipelineRunRead.model_validate(db_pipeline_run) 