import pytest
import pytest_asyncio
from unittest.mock import MagicMock, patch, AsyncMock
import uuid
from datetime import datetime, timezone

from sqlmodel import Session, select
from fastapi import HTTPException

from app.services.pipeline_service import (
    create_and_dispatch_summary_pipeline,
    get_pipeline_run_status
)
from app.models.pipeline_models import (
    PipelineRun, PipelineRunCreate, PipelineRunRead, PipelineRunStatus, PipelineType
)
from app.models.file_models import UploadedFileLog

# Reusable mock for db session
@pytest_asyncio.fixture
def mock_db_session():
    session = MagicMock(spec=Session)
    session.add = MagicMock()
    session.commit = MagicMock()
    session.refresh = MagicMock()
    session.get = MagicMock()
    session.exec = MagicMock()
    return session

@pytest_asyncio.fixture
def mock_uploaded_file_log():
    log = UploadedFileLog(
        id=1,
        file_uuid=uuid.uuid4(),
        filename="test.pdf",
        content_type="application/pdf",
        size_bytes=1024,
        storage_location="./uploaded_files/test.pdf",
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc)
    )
    return log

@pytest_asyncio.fixture
def mock_pipeline_run():
    run_uuid = uuid.uuid4()
    pr = PipelineRun(
        id=1,
        run_uuid=run_uuid,
        pipeline_name=PipelineType.PDF_SUMMARIZER,
        status=PipelineRunStatus.QUEUED,
        uploaded_file_log_id=1,
        celery_task_id=str(uuid.uuid4()),
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc)
    )
    return pr

@pytest.mark.asyncio
async def test_create_and_dispatch_summary_pipeline_success(
    mock_db_session: MagicMock, 
    mock_uploaded_file_log: UploadedFileLog
):
    """Test successful creation and dispatch of a summary pipeline."""
    mock_db_session.get.return_value = mock_uploaded_file_log
    
    mock_celery_task_result = MagicMock()
    mock_celery_task_result.id = str(uuid.uuid4())

    # Capture the PipelineRun instance passed to db.add and db.refresh
    # and simulate the refresh by adding an id and celery_task_id to it.
    captured_pipeline_run = None

    def refresh_side_effect(obj):
        nonlocal captured_pipeline_run
        if isinstance(obj, PipelineRun):
            obj.id = 1 # Simulate DB assigning an ID
            obj.celery_task_id = mock_celery_task_result.id # Simulate celery task ID assignment
            captured_pipeline_run = obj

    mock_db_session.refresh.side_effect = refresh_side_effect

    # Also ensure that when db.add is called, subsequent db.refresh uses the same object with generated run_uuid
    def add_side_effect(obj):
        nonlocal captured_pipeline_run
        if isinstance(obj, PipelineRun):
            # The run_uuid is generated by default_factory in PipelineRunCreate/PipelineRun
            # So, we don't need to manually set it here if the model works correctly.
            # We will capture it to verify.
            captured_pipeline_run = obj 

    mock_db_session.add.side_effect = add_side_effect

    with patch("app.services.pipeline_service.summarize_pdf_task.delay", return_value=mock_celery_task_result) as mock_delay:
        response = await create_and_dispatch_summary_pipeline(1, mock_db_session)

    mock_db_session.get.assert_called_once_with(UploadedFileLog, 1)
    
    # add is called twice: once for initial PipelineRun, once for updating with celery_task_id
    assert mock_db_session.add.call_count == 2 
    # commit is called twice
    assert mock_db_session.commit.call_count == 2
    # refresh is called twice
    assert mock_db_session.refresh.call_count == 2

    # Check the captured PipelineRun from the refresh_side_effect or add_side_effect
    assert captured_pipeline_run is not None
    assert captured_pipeline_run.pipeline_name == PipelineType.PDF_SUMMARIZER
    assert captured_pipeline_run.status == PipelineRunStatus.QUEUED
    assert captured_pipeline_run.uploaded_file_log_id == 1
    assert captured_pipeline_run.celery_task_id == mock_celery_task_result.id
    assert isinstance(captured_pipeline_run.run_uuid, uuid.UUID)

    mock_delay.assert_called_once_with(
        str(captured_pipeline_run.run_uuid),
        mock_uploaded_file_log.id,
        mock_uploaded_file_log.storage_location,
        mock_uploaded_file_log.filename
    )

    assert isinstance(response, PipelineRunRead)
    assert response.run_uuid == captured_pipeline_run.run_uuid
    assert response.celery_task_id == mock_celery_task_result.id
    assert response.status == PipelineRunStatus.QUEUED

@pytest.mark.asyncio
async def test_create_and_dispatch_file_not_found(mock_db_session: MagicMock):
    """Test pipeline creation when uploaded file log is not found."""
    mock_db_session.get.return_value = None
    with pytest.raises(HTTPException) as exc_info:
        await create_and_dispatch_summary_pipeline(999, mock_db_session)
    assert exc_info.value.status_code == 404
    assert "UploadedFileLog with id 999 not found" in exc_info.value.detail
    mock_db_session.add.assert_not_called()
    mock_db_session.commit.assert_not_called()

@pytest.mark.asyncio
async def test_create_and_dispatch_pdf_path_not_found_in_log(mock_db_session: MagicMock):
    """Test pipeline creation when uploaded file log has no storage_location."""
    mock_file_log_no_path = UploadedFileLog(
        id=2, filename="test_no_path.pdf", storage_location=None # Key for this test
    )
    mock_db_session.get.return_value = mock_file_log_no_path

    # Capture the PipelineRun to check its status after the error
    captured_pipeline_run = None
    def refresh_side_effect(obj):
        nonlocal captured_pipeline_run
        if isinstance(obj, PipelineRun):
            obj.id = 2 # Simulate DB assigning an ID
            captured_pipeline_run = obj
    mock_db_session.refresh.side_effect = refresh_side_effect
    
    def add_side_effect(obj):
        nonlocal captured_pipeline_run
        if isinstance(obj, PipelineRun):
             captured_pipeline_run = obj
    mock_db_session.add.side_effect = add_side_effect

    with pytest.raises(HTTPException) as exc_info, \
         patch("app.services.pipeline_service.summarize_pdf_task.delay") as mock_delay:
        await create_and_dispatch_summary_pipeline(2, mock_db_session)
    
    assert exc_info.value.status_code == 500
    assert "PDF path not found for dispatching task" in exc_info.value.detail

    # Initial add/commit/refresh for PipelineRun creation
    # Second add/commit for updating status to FAILED
    assert mock_db_session.add.call_count == 2
    assert mock_db_session.commit.call_count == 2
    assert mock_db_session.refresh.call_count == 1 # Only first refresh happens

    assert captured_pipeline_run is not None
    assert captured_pipeline_run.status == PipelineRunStatus.FAILED
    assert captured_pipeline_run.error_message == "PDF path not found in UploadedFileLog."
    mock_delay.assert_not_called()

@pytest.mark.asyncio
async def test_create_and_dispatch_celery_dispatch_failure(
    mock_db_session: MagicMock, 
    mock_uploaded_file_log: UploadedFileLog
):
    """Test pipeline creation when Celery task dispatch fails."""
    mock_db_session.get.return_value = mock_uploaded_file_log

    captured_pipeline_run = None
    def refresh_side_effect(obj):
        nonlocal captured_pipeline_run
        if isinstance(obj, PipelineRun):
            obj.id = 1 # Simulate DB assigning an ID
            # Do not assign celery_task_id here as dispatch will fail
            captured_pipeline_run = obj
    mock_db_session.refresh.side_effect = refresh_side_effect

    def add_side_effect(obj):
        nonlocal captured_pipeline_run
        if isinstance(obj, PipelineRun):
             captured_pipeline_run = obj
    mock_db_session.add.side_effect = add_side_effect

    with patch("app.services.pipeline_service.summarize_pdf_task.delay", side_effect=Exception("Celery down")) as mock_delay, \
         pytest.raises(HTTPException) as exc_info:
        await create_and_dispatch_summary_pipeline(1, mock_db_session)

    assert exc_info.value.status_code == 500
    assert "Failed to dispatch summarization task: Celery down" in exc_info.value.detail

    mock_delay.assert_called_once()
    # add/commit/refresh for initial PipelineRun + add/commit/refresh for FAILED status update
    assert mock_db_session.add.call_count == 2
    assert mock_db_session.commit.call_count == 2
    assert mock_db_session.refresh.call_count == 2 # Both refreshes happen

    assert captured_pipeline_run is not None
    assert captured_pipeline_run.status == PipelineRunStatus.FAILED
    assert "Failed to dispatch Celery task: Celery down" in captured_pipeline_run.error_message


@pytest.mark.asyncio
async def test_get_pipeline_run_status_found(mock_db_session: MagicMock, mock_pipeline_run: PipelineRun):
    """Test successfully retrieving a pipeline run status."""
    mock_query_result = MagicMock()
    mock_query_result.one_or_none.return_value = mock_pipeline_run
    mock_db_session.exec.return_value = mock_query_result

    response = await get_pipeline_run_status(mock_pipeline_run.run_uuid, mock_db_session)

    mock_db_session.exec.assert_called_once()
    # We need to assert that the select statement was constructed correctly.
    # This is a bit tricky with MagicMock. We can check the first arg of exec.
    args, _ = mock_db_session.exec.call_args
    assert isinstance(args[0], type(select(PipelineRun)))
    # Further inspection of the select object would be complex and test SQLModel internals.
    # For now, ensuring it's a select and one_or_none is called is sufficient for this mock level.

    assert isinstance(response, PipelineRunRead)
    assert response.run_uuid == mock_pipeline_run.run_uuid
    assert response.status == mock_pipeline_run.status

@pytest.mark.asyncio
async def test_get_pipeline_run_status_not_found(mock_db_session: MagicMock):
    """Test retrieving status for a non-existent pipeline run."""
    mock_query_result = MagicMock()
    mock_query_result.one_or_none.return_value = None
    mock_db_session.exec.return_value = mock_query_result
    run_uuid_not_found = uuid.uuid4()

    response = await get_pipeline_run_status(run_uuid_not_found, mock_db_session)

    mock_db_session.exec.assert_called_once()
    assert response is None

@pytest.mark.asyncio
async def test_create_and_dispatch_db_failure_initial_save(mock_db_session: MagicMock, mock_uploaded_file_log: UploadedFileLog):
    """Test DB failure during the initial save of PipelineRun."""
    mock_db_session.get.return_value = mock_uploaded_file_log
    mock_db_session.commit.side_effect = [Exception("DB error on first commit"), None] # Fail first commit, succeed second (if any)
    # We expect it to not even reach the point of dispatching the Celery task.

    with pytest.raises(Exception) as exc_info, \
         patch("app.services.pipeline_service.summarize_pdf_task.delay") as mock_delay:
        # The service function re-raises the original DB exception if not caught by specific logic
        # In this case, the first commit failing isn't specifically handled to update status to FAILED,
        # so it should propagate the raw DB error.
        await create_and_dispatch_summary_pipeline(1, mock_db_session)

    assert str(exc_info.value) == "DB error on first commit"
    mock_db_session.get.assert_called_once_with(UploadedFileLog, 1)
    mock_db_session.add.assert_called_once() # Called once for the initial PipelineRun
    mock_db_session.commit.assert_called_once() # Called once, and it failed
    mock_db_session.refresh.assert_not_called() # Should not be called if commit fails
    mock_delay.assert_not_called()
